replicaCount: 1

image:
  repository: "melanief/hashGenerator"
  pullPolicy: IfNotPresent
  tag: "v1.0"

serviceAccount:
  create: false
  automount: false
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 1
    memory: 2Gi
